#!/bin/bash
# Build the Next.js app
echo "Building Next.js frontend..."
npx next build

# Create the static directory in the API folder if it doesn't exist
mkdir -p api/static

# Copy the built files to the API static directory
echo "Copying built files to API static directory..."
cp -r out/* api/static/

# Create runtime configuration file
echo "Creating runtime configuration file..."
cat > api/static/config.js << EOF
// Runtime configuration for RSW application
// This file is automatically generated during the build process
window.__RSW_CONFIG__ = {
  apiBaseUrl: window.location.origin
};
EOF

# Update index.html to include the config.js script
echo "Updating HTML files to include runtime configuration..."
for htmlfile in api/static/*.html; do
  if [ -f "$htmlfile" ]; then
    # Insert the script tag before the first existing script tag
    sed -i '' 's/<script/<script src="\/config.js"><\/script>\n<script/' "$htmlfile"
  fi
done

echo "Frontend build complete and copied to API static directory!"
